apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
# Usamos stringData para poder escribir en texto plano. K8s lo encriptará por nosotros.
stringData: 
  DB_USER: user_GA
  DB_PASSWORD: password_db
  DB_NAME: groups_db
