---
apiVersion: v1
kind: Service
metadata:
  name: groups-service
spec:
  selector:
    app: groups-grpc
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: groups-deployment
spec:
  replicas: 1 # ----------- REPLICAS ----------- REPLICAS ----------- REPLICAS ----------- REPLICAS -----------
  selector:
    matchLabels:
      app: groups-grpc
  template:
    metadata:
      labels:
        app: groups-grpc
    spec:
      containers:
      - name: groups-grpc
        image: gruops-app_micro-groups-grpc:latest
        imagePullPolicy: Never
        command: ["python3", "-m", "modules.groups.grpc_server"]
        ports:
        - containerPort: 50052
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_NAME
        - name: DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@postgres-service:5432/$(DB_NAME)"