---
apiVersion: v1
kind: Service
metadata:
  name: groups-service
spec:
  selector:
    app: groups-grpc
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: groups-deployment
spec:
  replicas: 1 # ----------- REPLICAS ----------- REPLICAS ----------- REPLICAS ----------- REPLICAS -----------
  selector:
    matchLabels:
      app: groups-grpc
  template:
    metadata:
      labels:
        app: groups-grpc
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv postgres-service 5432; do echo waiting for postgres; sleep 2; done;"]
      containers:
      - name: groups-grpc
        #image: tu-usuario/gruops-app_micro-groups-grpc:latest
        image: 297570491771.dkr.ecr.us-east-1.amazonaws.com/groupsapp-backend:latest
        imagePullPolicy: Never
        command: ["python3", "-m", "modules.groups.grpc_server"]
        ports:
        - containerPort: 50052
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_NAME
        - name: DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@groups-app-db.cluster-ciphu7kcxcvs.us-east-1.rds.amazonaws.com:5432/auth_db"