---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: LoadBalancer 
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      # 🛡️ Paso 1: Esperar físicamente a que el puerto de Postgres abra
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv postgres-service 5432; do echo waiting for postgres; sleep 2; done;"]
      
      containers:
      - name: api-gateway
        image: 297570491771.dkr.ecr.us-east-1.amazonaws.com/groupsapp-backend:latest
        imagePullPolicy: Never
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        
        # 🏥 Paso 2: Verificar que la app esté lista para recibir tráfico
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20

        envFrom:
        - configMapRef:
            name: app-config 
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef: {name: app-secrets, key: DB_USER}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef: {name: app-secrets, key: DB_PASSWORD}
        - name: DB_NAME
          valueFrom:
            secretKeyRef: {name: app-secrets, key: DB_NAME}
        - name: DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@groups-app-db.cluster-ciphu7kcxcvs.us-east-1.rds.amazonaws.com:5432/auth_db"