# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/auth.proto\x12\x04\x61uth\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"D\n\rTokenResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x10\n\x08username\x18\x03 \x01(\t\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"S\n\x0cUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x11\n\tis_active\x18\x04 \x01(\x08\x32y\n\x0b\x41uthService\x12\x38\n\rValidateToken\x12\x12.auth.TokenRequest\x1a\x13.auth.TokenResponse\x12\x30\n\x07GetUser\x12\x11.auth.UserRequest\x1a\x12.auth.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENREQUEST']._serialized_start=27
  _globals['_TOKENREQUEST']._serialized_end=56
  _globals['_TOKENRESPONSE']._serialized_start=58
  _globals['_TOKENRESPONSE']._serialized_end=126
  _globals['_USERREQUEST']._serialized_start=128
  _globals['_USERREQUEST']._serialized_end=158
  _globals['_USERRESPONSE']._serialized_start=160
  _globals['_USERRESPONSE']._serialized_end=243
  _globals['_AUTHSERVICE']._serialized_start=245
  _globals['_AUTHSERVICE']._serialized_end=366
# @@protoc_insertion_point(module_scope)
