# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import groups_pb2 as protos_dot_groups__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/groups_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GroupServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckMembership = channel.unary_unary(
                '/groups.GroupService/CheckMembership',
                request_serializer=protos_dot_groups__pb2.MembershipRequest.SerializeToString,
                response_deserializer=protos_dot_groups__pb2.MembershipResponse.FromString,
                _registered_method=True)
        self.GetGroupMembers = channel.unary_unary(
                '/groups.GroupService/GetGroupMembers',
                request_serializer=protos_dot_groups__pb2.GroupRequest.SerializeToString,
                response_deserializer=protos_dot_groups__pb2.GroupMembersResponse.FromString,
                _registered_method=True)


class GroupServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckMembership(self, request, context):
        """Verifica la relación Muchos a Muchos entre usuarios y grupos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckMembership': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckMembership,
                    request_deserializer=protos_dot_groups__pb2.MembershipRequest.FromString,
                    response_serializer=protos_dot_groups__pb2.MembershipResponse.SerializeToString,
            ),
            'GetGroupMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupMembers,
                    request_deserializer=protos_dot_groups__pb2.GroupRequest.FromString,
                    response_serializer=protos_dot_groups__pb2.GroupMembersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'groups.GroupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('groups.GroupService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GroupService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckMembership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groups.GroupService/CheckMembership',
            protos_dot_groups__pb2.MembershipRequest.SerializeToString,
            protos_dot_groups__pb2.MembershipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/groups.GroupService/GetGroupMembers',
            protos_dot_groups__pb2.GroupRequest.SerializeToString,
            protos_dot_groups__pb2.GroupMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
