# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: groups.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'groups.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgroups.proto\x12\x06groups\"6\n\x11MembershipRequest\x12\x10\n\x08group_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"9\n\x12MembershipResponse\x12\x11\n\tis_member\x18\x01 \x01(\x08\x12\x10\n\x08is_admin\x18\x02 \x01(\x08\x32X\n\x0cGroupService\x12H\n\x0f\x43heckMembership\x12\x19.groups.MembershipRequest\x1a\x1a.groups.MembershipResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'groups_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEMBERSHIPREQUEST']._serialized_start=24
  _globals['_MEMBERSHIPREQUEST']._serialized_end=78
  _globals['_MEMBERSHIPRESPONSE']._serialized_start=80
  _globals['_MEMBERSHIPRESPONSE']._serialized_end=137
  _globals['_GROUPSERVICE']._serialized_start=139
  _globals['_GROUPSERVICE']._serialized_end=227
# @@protoc_insertion_point(module_scope)
