# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/groups.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/groups.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/groups.proto\x12\x06groups\"6\n\x11MembershipRequest\x12\x10\n\x08group_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"9\n\x12MembershipResponse\x12\x11\n\tis_member\x18\x01 \x01(\x08\x12\x10\n\x08is_admin\x18\x02 \x01(\x08\" \n\x0cGroupRequest\x12\x10\n\x08group_id\x18\x01 \x01(\x05\"(\n\x14GroupMembersResponse\x12\x10\n\x08user_ids\x18\x01 \x03(\x05\x32\x9f\x01\n\x0cGroupService\x12H\n\x0f\x43heckMembership\x12\x19.groups.MembershipRequest\x1a\x1a.groups.MembershipResponse\x12\x45\n\x0fGetGroupMembers\x12\x14.groups.GroupRequest\x1a\x1c.groups.GroupMembersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.groups_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEMBERSHIPREQUEST']._serialized_start=31
  _globals['_MEMBERSHIPREQUEST']._serialized_end=85
  _globals['_MEMBERSHIPRESPONSE']._serialized_start=87
  _globals['_MEMBERSHIPRESPONSE']._serialized_end=144
  _globals['_GROUPREQUEST']._serialized_start=146
  _globals['_GROUPREQUEST']._serialized_end=178
  _globals['_GROUPMEMBERSRESPONSE']._serialized_start=180
  _globals['_GROUPMEMBERSRESPONSE']._serialized_end=220
  _globals['_GROUPSERVICE']._serialized_start=223
  _globals['_GROUPSERVICE']._serialized_end=382
# @@protoc_insertion_point(module_scope)
