# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import presence_pb2 as protos_dot_presence__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/presence_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PresenceServiceStub(object):
    """El servicio de presencia
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateStatus = channel.unary_unary(
                '/presence.PresenceService/UpdateStatus',
                request_serializer=protos_dot_presence__pb2.StatusUpdateRequest.SerializeToString,
                response_deserializer=protos_dot_presence__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetUserStatus = channel.unary_unary(
                '/presence.PresenceService/GetUserStatus',
                request_serializer=protos_dot_presence__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=protos_dot_presence__pb2.StatusResponse.FromString,
                _registered_method=True)


class PresenceServiceServicer(object):
    """El servicio de presencia
    """

    def UpdateStatus(self, request, context):
        """Para que el Gateway avise cuando alguien se conecta/desconecta
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserStatus(self, request, context):
        """Para consultar si alguien está online
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PresenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatus,
                    request_deserializer=protos_dot_presence__pb2.StatusUpdateRequest.FromString,
                    response_serializer=protos_dot_presence__pb2.StatusResponse.SerializeToString,
            ),
            'GetUserStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserStatus,
                    request_deserializer=protos_dot_presence__pb2.GetStatusRequest.FromString,
                    response_serializer=protos_dot_presence__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'presence.PresenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('presence.PresenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PresenceService(object):
    """El servicio de presencia
    """

    @staticmethod
    def UpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/presence.PresenceService/UpdateStatus',
            protos_dot_presence__pb2.StatusUpdateRequest.SerializeToString,
            protos_dot_presence__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/presence.PresenceService/GetUserStatus',
            protos_dot_presence__pb2.GetStatusRequest.SerializeToString,
            protos_dot_presence__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
